# Site settings
title: Ricardo's Blog
description: Testing # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: #http://rkrdo.github.io # the base hostname & protocol for your site
reading_time: true
words_per_minute: 100

# Build settings
timezone:    America/New_York
future:      true
highlighter: pygments
markdown: kramdown

# HPSTR configurations
disqus_shortname: rkrdo-blog
google_analytics_tracking_id: UA-44600145-1
#permalink:   /:categories/:title/


owner:
  name: Ricardo Cruz
  bio: Rails developer, vim/tmux fanboy.
  avatar: https://media.licdn.com/media/p/3/000/20f/125/09bab6f.jpg
  email: ricardocruz.a89@gmail.com
  twitter: rkrdox
  github: rkrdo
  linkedin: ricardocruz89

paginate: 5
